"""init §6 — 4 tables verified

Revision ID: 510f6e0fcc4e
Revises:
Create Date: 2026-08-15 01:43:31.155031
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "510f6e0fcc4e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "po_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("po_no_normalized", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "mismatched",
                "quarantined",
                "blocked_customs",
                "merged",
                name="posetstatus",
            ),
            nullable=False,
        ),
        sa.Column("has_customs_toggle", sa.Boolean(), nullable=False),
        sa.Column("customs_doc_count", sa.Integer(), nullable=False),
        sa.Column("merged_output_path", sa.Text(), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by_action", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_po_sets_po_no_normalized"), "po_sets", ["po_no_normalized"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("po_set_id", sa.Integer(), nullable=True),
        sa.Column(
            "action",
            sa.Enum("force_merge", "quarantine_delete", "manual_status_change", name="auditaction"),
            nullable=False,
        ),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["po_set_id"],
            ["po_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256_hash", sa.String(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum(
                "PO",
                "DN",
                "SI",
                "COMBINED",
                "CUSTOMS",
                "SHIPPING",
                "COMMERCIAL_INVOICE",
                "UNKNOWN",
                name="doctype",
            ),
            nullable=False,
        ),
        sa.Column("po_no_raw", sa.Text(), nullable=True),
        sa.Column("po_no_normalized", sa.Text(), nullable=True),
        sa.Column("dn_no", sa.Text(), nullable=True),
        sa.Column("si_no", sa.Text(), nullable=True),
        sa.Column("invoice_no", sa.Text(), nullable=True),
        sa.Column(
            "extraction_status",
            sa.Enum("pending", "processing", "valid", "failed", name="extractionstatus"),
            nullable=False,
        ),
        sa.Column("extraction_attempt_count", sa.Integer(), nullable=False),
        sa.Column("po_set_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["po_set_id"],
            ["po_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_documents_po_no_normalized", "documents", ["po_no_normalized"], unique=False
    )
    op.create_index(op.f("ix_documents_sha256_hash"), "documents", ["sha256_hash"], unique=True)
    op.create_table(
        "line_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("line_item_no", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("line_items")
    op.drop_index(op.f("ix_documents_sha256_hash"), table_name="documents")
    op.drop_index("ix_documents_po_no_normalized", table_name="documents")
    op.drop_table("documents")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_po_sets_po_no_normalized"), table_name="po_sets")
    op.drop_table("po_sets")
    # ### end Alembic commands ###
